version: '3.1'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: thisIsAPasswordFrom2023?
      MYSQL_DATABASE: scrapping
    ports:
      - 3344:3306
    volumes:
      - './volumes/mysql/:/var/lib/mysql'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    environment:
      ADMINER_DESIGN: flat
      ADMINER_PLUGINS: tables-filter tinymce edit-textarea edit-foreign enum-option frames edit-calendar